# Generated by Django 3.1.5 on 2021-07-26 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='owner',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='balance_month_year',
            new_name='date_reference',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='account',
            new_name='id_account',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_credit',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_credit_spent',
            new_name='credit_spent',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='account',
            new_name='id_account',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_pay_date',
            new_name='pay_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_month_year',
            new_name='date_reference',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='card',
            new_name='id_card',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='is_invoice_paid',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='release_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='repeat_date',
            new_name='date_repeat',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='release_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='releasecategory',
            old_name='owner',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='releasecategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='total_available',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='total_expense',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='total_income',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.RemoveField(
            model_name='release',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='release',
            name='invoice',
        ),
        migrations.CreateModel(
            name='InvoiceRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economeeApi.invoice')),
                ('id_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economeeApi.release')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economeeApi.balance')),
                ('id_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economeeApi.release')),
            ],
        ),
    ]
