# Generated by Django 3.1.5 on 2021-08-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0002_auto_20210725_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_available',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='total_expense',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balance',
            name='total_income',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='type',
            field=models.CharField(blank=True, choices=[('PR', 'Projection'), ('ER', 'Expense'), ('IR', 'Income')], max_length=2, verbose_name='Release Type'),
        ),
    ]
