# Generated by Django 3.1.5 on 2021-01-09 15:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0002_auto_20210109_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='economeeApi.balance'),
        ),
        migrations.AlterField(
            model_name='release',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 9, 15, 47, 26, 797864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='release',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='economeeApi.invoice'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='economeeApi.releasecategory'),
        ),
        migrations.AlterField(
            model_name='release',
            name='repeat_date',
            field=models.DateField(default=models.DateField(default=datetime.datetime(2021, 1, 9, 15, 47, 26, 797864, tzinfo=utc))),
        ),
        migrations.AlterField(
            model_name='releasecategory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
