# Generated by Django 3.1.5 on 2021-08-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0003_auto_20210808_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
            ],
        ),
    ]
