# Generated by Django 3.1.5 on 2021-01-11 00:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0003_auto_20210109_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='installment_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='release',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 11, 0, 27, 1, 383910, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='release',
            name='repeat_date',
            field=models.DateField(default=models.DateField(default=datetime.datetime(2021, 1, 11, 0, 27, 1, 383910, tzinfo=utc))),
        ),
    ]
