# Generated by Django 3.1.5 on 2021-08-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0004_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='id_account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='balancerelease',
            old_name='id_balance',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='balancerelease',
            old_name='id_release',
            new_name='release',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='id_account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='id_card',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='invoicerelease',
            old_name='id_invoice',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='invoicerelease',
            old_name='id_release',
            new_name='release',
        ),
        migrations.RenameField(
            model_name='releasecategory',
            old_name='id_user',
            new_name='user',
        ),
    ]
