# Generated by Django 3.1.5 on 2021-01-11 00:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0004_auto_20210110_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='date',
        ),
        migrations.AddField(
            model_name='release',
            name='date_release',
            field=models.DateField(default=datetime.datetime(2021, 1, 11, 0, 38, 35, 430362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='release',
            name='repeat_date',
            field=models.DateField(),
        ),
    ]
