# Generated by Django 3.1.5 on 2021-01-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0005_auto_20210110_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='date_release',
            field=models.DateField(),
        ),
    ]
