# Generated by Django 3.1.5 on 2021-08-13 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0005_auto_20210812_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economeeApi.currency'),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_available',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='total_expense',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='balance',
            name='total_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='card',
            name='credit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='card',
            name='credit_spent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
