# Generated by Django 3.1.5 on 2021-08-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0006_auto_20210812_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasecategory',
            name='name',
            field=models.CharField(max_length=124),
        ),
    ]
