# Generated by Django 3.1.5 on 2021-08-15 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0007_auto_20210812_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economeeApi.invoice')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economeeApi.release')),
            ],
        ),
    ]
