# Generated by Django 3.1.5 on 2021-08-16 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0008_balanceinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceinvoice',
            name='release',
        ),
        migrations.AddField(
            model_name='balanceinvoice',
            name='balance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='economeeApi.balance'),
            preserve_default=False,
        ),
    ]
