# Generated by Django 3.1.5 on 2021-08-16 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0009_auto_20210815_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancerelease',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='balancerelease',
            name='release',
        ),
        migrations.RemoveField(
            model_name='invoicerelease',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoicerelease',
            name='release',
        ),
        migrations.RemoveField(
            model_name='account',
            name='total_available',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='total_expense',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='total_income',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='economeeApi.balance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='economeeApi.balance'),
        ),
        migrations.AddField(
            model_name='release',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='economeeApi.invoice'),
        ),
        migrations.DeleteModel(
            name='BalanceInvoice',
        ),
        migrations.DeleteModel(
            name='BalanceRelease',
        ),
        migrations.DeleteModel(
            name='InvoiceRelease',
        ),
    ]
