# Generated by Django 3.1.5 on 2021-08-16 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0010_auto_20210816_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='economeeApi.account'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='economeeApi.balance'),
        ),
        migrations.AlterField(
            model_name='release',
            name='balance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='releases', to='economeeApi.balance'),
        ),
        migrations.AlterField(
            model_name='release',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='releases', to='economeeApi.invoice'),
        ),
    ]
