# Generated by Django 3.1.5 on 2021-08-16 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0011_auto_20210816_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='economeeApi.account'),
        ),
    ]
