# Generated by Django 3.1.5 on 2021-08-17 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0012_auto_20210816_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='economeeApi.card'),
        ),
    ]
