# Generated by Django 3.1.5 on 2021-08-18 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0013_auto_20210816_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='credit_spent',
        ),
    ]
