# Generated by Django 3.1.5 on 2021-08-21 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0015_remove_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
