# Generated by Django 3.1.5 on 2021-09-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0017_auto_20210825_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='date_creation',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='release',
            name='value_installment',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='release',
            name='date_release',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='date_repeat',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
