# Generated by Django 3.1.5 on 2021-09-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0019_auto_20210905_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='date_creation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='release',
            name='date_release',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='release',
            name='date_repeat',
            field=models.DateField(),
        ),
    ]
