# Generated by Django 3.2.7 on 2021-09-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0020_auto_20210905_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasecategory',
            name='color',
            field=models.CharField(default='white', max_length=124),
            preserve_default=False,
        ),
    ]
