# Generated by Django 3.2.7 on 2021-09-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0022_remove_releasecategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasecategory',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
