# Generated by Django 3.2.7 on 2021-09-21 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0023_releasecategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasecategory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
