# Generated by Django 3.2.7 on 2021-10-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0024_alter_releasecategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='balance',
        ),
    ]
