# Generated by Django 3.2.7 on 2022-01-31 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0025_remove_invoice_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasecategory',
            name='type',
        ),
    ]
