# Generated by Django 3.2.7 on 2022-02-20 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0026_remove_releasecategory_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='is_release_paid',
            new_name='is_paid',
        ),
        migrations.RenameField(
            model_name='releasecategory',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='release',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='release',
            name='date_release',
        ),
        migrations.RemoveField(
            model_name='release',
            name='date_repeat',
        ),
        migrations.RemoveField(
            model_name='release',
            name='installment_number',
        ),
        migrations.RemoveField(
            model_name='release',
            name='installment_value',
        ),
        migrations.RemoveField(
            model_name='release',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='release',
            name='repeat_times',
        ),
        migrations.AddField(
            model_name='balance',
            name='total_expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='balance',
            name='total_incomes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='date_reference',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='pay_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_reference',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='release',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='releases', to='economeeApi.releasecategory'),
        ),
        migrations.AlterField(
            model_name='release',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='type',
            field=models.IntegerField(choices=[(0, 'Expense'), (1, 'Income')], verbose_name='Release Type'),
        ),
        migrations.CreateModel(
            name='RecurringRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_release', models.DateField()),
                ('installment', models.IntegerField(default=1)),
                ('installment_number', models.IntegerField(default=1)),
                ('installment_value', models.FloatField(default=0.0)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='economeeApi.balance')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='economeeApi.invoice')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release', to='economeeApi.release')),
            ],
        ),
    ]
