# Generated by Django 3.2.7 on 2022-02-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0027_auto_20220220_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringrelease',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='recurringrelease',
            name='invoice',
        ),
        migrations.AddField(
            model_name='release',
            name='balance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='balance', to='economeeApi.balance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='economeeApi.invoice'),
        ),
    ]
