# Generated by Django 3.2.7 on 2022-02-20 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0029_auto_20220220_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringrelease',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_release', to='economeeApi.balance'),
        ),
        migrations.AlterField(
            model_name='recurringrelease',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_release', to='economeeApi.invoice'),
        ),
        migrations.AlterField(
            model_name='recurringrelease',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_release', to='economeeApi.release'),
        ),
    ]
