# Generated by Django 3.2.7 on 2022-02-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0030_auto_20220220_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='recurringrelease',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
