# Generated by Django 3.2.7 on 2022-03-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0031_auto_20220220_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_available',
            field=models.FloatField(default=0.0),
        ),
    ]
