# Generated by Django 3.2.7 on 2022-03-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0034_auto_20220302_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringrelease',
            name='installment',
        ),
        migrations.AddField(
            model_name='recurringrelease',
            name='installment_total',
            field=models.IntegerField(default=1),
        ),
    ]
