# Generated by Django 3.2.7 on 2022-04-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0036_rename_installment_total_recurringrelease_installment_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasecategory',
            name='color',
            field=models.CharField(default=0, max_length=124),
            preserve_default=False,
        ),
    ]
