# Generated by Django 4.2.10 on 2024-03-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economeeApi', '0038_alter_card_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='date_reference',
            new_name='reference_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='date_reference',
            new_name='reference_date',
        ),
        migrations.RenameField(
            model_name='recurringrelease',
            old_name='date_release',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='release',
            old_name='date_creation',
            new_name='creation_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
